-- =============================
-- ユーザーテーブル
-- =============================
CREATE TABLE users (
    user_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,         -- 自動連番（ユーザーID）
    user_name VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =============================
-- タスクステイトテーブル（状態マスタ）
-- =============================
CREATE TABLE task_state (
    state_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,        -- 自動連番（状態ID）
    state_name VARCHAR(10) NOT NULL
);

-- =============================
-- タスクテーブル
-- =============================
CREATE TABLE tasks (
    task_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,         -- 自動連番（タスクID）
    task_name VARCHAR(50) NOT NULL,
    importance INTEGER,
    urgency INTEGER,
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id INTEGER NOT NULL,
    state_id INTEGER DEFAULT 1  NOT NULL,        -- 状態を必須とする
    CONSTRAINT fk_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE,              -- 親のusersが削除されたら関連タスクも削除
    CONSTRAINT fk_state
        FOREIGN KEY (state_id)
        REFERENCES task_state(state_id)
        ON DELETE RESTRICT              -- 状態削除を禁止（マスタ固定）
);

-- =============================
-- 外部キー用のインデックス
-- =============================
CREATE INDEX idx_tasks_user_id  ON tasks(user_id);
CREATE INDEX idx_tasks_state_id ON tasks(state_id);

-- 外部キー制約があると親テーブルで参照元のデータが削除されたとき
-- 該当するキーで一覧検索やjoinを行いデータをセレクトしたとき
-- などに素早くデータの取得ができる。indexがないと該当データ全てから条件に合うものを探すことになる。

-- 自動連番の記述方法に　serial という記述方法がある。　serialはposgre独自の古い書き方であるため非推奨
-- user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 